## Exercise 6: Shared utility functions, data catalogs

Skills: 
* Import shared utils
* Data catalog
* Use functions to repeat certain data cleaning steps

References: 
* https://docs.calitp.org/data-infra/analytics_new_analysts/02-data-analysis-intermediate.html
* https://docs.calitp.org/data-infra/analytics_tools/python_libraries.html
* https://docs.calitp.org/data-infra/analytics_tools/data_catalogs.html

In [1]:
import geopandas as gpd
import intake
import pandas as pd

from calitp_data_analysis import geography_utils, utils
from calitp_data_analysis import styleguide

# Hint: if this doesn't import: refer to docs for correctly import
# cd into _shared_utils folder, run the make setup_env command
from shared_utils import portfolio_utils

## Create a data catalog

* Include one geospatial data source and one tabular (they should be related...your analysis depends on combining them)
* Import your datasets using the catalog method

In [31]:
catalog = intake.open_catalog("sample_catalog.yml")

In [32]:
counties = catalog.caltrans_open_data.ca_county_boundaries.read()
counties.head()

,OBJECTID,COUNTYFP10,GEOID10,NAME10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,CO_CODE,DISTRICT,SHAPE_Length,SHAPE_Area,geometry
0,1,059,06059,Orange,2.047561e+09,4.079168e+08,+33.6756872,-117.7772068,ORA,12,2.978872,0.200321,"MULTIPOLYGON (((-117.91576 33.94693, -117.9156..."
1,2,103,06103,Tehama,7.639710e+09,3.227606e+07,+40.1261561,-122.2322757,TEH,2,5.152453,0.810614,"MULTIPOLYGON (((-121.68552 40.45308, -121.6854..."
2,3,011,06011,Colusa,2.980379e+09,1.458102e+07,+39.1777385,-122.2375629,COL,3,3.212895,0.312200,"MULTIPOLYGON (((-122.10654 39.41442, -122.1027..."
3,4,083,06083,Santa Barbara,7.083838e+09,2.729829e+09,+34.5373784,-120.0384850,SB,5,4.252901,0.651046,"MULTIPOLYGON (((-120.07950 35.11300, -120.0793..."
4,5,051,06051,Mono,7.896827e+09,2.146955e+08,+37.9158363,-118.8751668,MNO,9,5.686027,0.830964,"MULTIPOLYGON (((-117.83340 37.46494, -117.8348..."

In [33]:
federal_jobs = catalog.lehd_federal_jobs_by_tract.read()
federal_jobs.head()

,st,stname,cty,ctyname,trct,trctname,year,c000,ca01,ca02,...,cr05,cr07,ct01,ct02,cd01,cd02,cd03,cd04,cs01,cs02
0,1,Alabama,1001,"Autauga County, AL",1001020100,"201 (Autauga, AL)",2011,3,0,2,...,0,0,3,0,0,3,0,0,0,3
1,1,Alabama,1001,"Autauga County, AL",1001020100,"201 (Autauga, AL)",2012,1,0,1,...,0,0,1,0,0,0,0,1,1,0
2,1,Alabama,1001,"Autauga County, AL",1001020100,"201 (Autauga, AL)",2013,2,0,1,...,0,0,2,0,0,2,0,0,2,0
3,1,Alabama,1001,"Autauga County, AL",1001020200,"202 (Autauga, AL)",2011,2,0,0,...,0,0,2,0,0,0,1,1,2,0
4,1,Alabama,1001,"Autauga County, AL",1001020200,"202 (Autauga, AL)",2012,4,0,3,...,0,0,4,0,0,0,3,1,3,1

## Combine datasets
* Do a merge or spatial join to combine the geospatial and tabular data
* Create a new column of a summary statistic to visualize
* Rely on `calitp_data_analysis` or `shared_utils` to do at least one operation (aggregation, re-projecting to a different CRS, exporting geoparquet, etc)
   * aggregation: `portfolio_utils.aggregate_by_geography`
   * exporting geoparquet: `calitp_data_analysis.utils.geoparquet_gcs_export`

In [61]:
federal_jobs_ca = federal_jobs.loc[federal_jobs["st"] == 6].copy()
federal_jobs_ca["county_three_digit"] = federal_jobs_ca["cty"].astype(str).str.slice(start=1)
federal_jobs_totals = federal_jobs_ca.drop(["st", "stname", "cty", "ctyname", "trct", "trctname", "year"], axis=1).groupby("county_three_digit").sum()
counties_with_federal_jobs = counties.merge(
    federal_jobs_totals,
    how="left",
    left_on="COUNTYFP10",
    right_index=True,
    validate="one_to_one"
).set_index("COUNTYFP10")
counties_with_federal_jobs

,OBJECTID,GEOID10,NAME10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,CO_CODE,DISTRICT,SHAPE_Length,...,cr05,cr07,ct01,ct02,cd01,cd02,cd03,cd04,cs01,cs02
COUNTYFP10,,,,,,,,,,,,,,,,,,,,,
059,1,06059,Orange,2.047561e+09,4.079168e+08,+33.6756872,-117.7772068,ORA,12,2.978872,...,280,2793,27903,6039,407,7062,7664,16004,16893,17049
103,2,06103,Tehama,7.639710e+09,3.227606e+07,+40.1261561,-122.2322757,TEH,2,5.152453,...,3,40,1118,63,2,251,264,555,753,428
011,3,06011,Colusa,2.980379e+09,1.458102e+07,+39.1777385,-122.2375629,COL,3,3.212895,...,60,188,4365,350,14,206,1417,2581,2170,2545
083,4,06083,Santa Barbara,7.083838e+09,2.729829e+09,+34.5373784,-120.0384850,SB,5,4.252901,...,40,744,7270,2068,27,3162,2455,2840,6225,3113
051,5,06051,Mono,7.896827e+09,2.146955e+08,+37.9158363,-118.8751668,MNO,9,5.686027,...,2,10,195,16,0,57,50,84,137,74
053,6,06053,Monterey,8.496703e+09,1.270714e+09,+36.2401070,-121.3155732,MON,5,6.542538,...,99,995,3849,2548,135,1739,2216,1885,2118,4279
061,7,06061,Placer,3.644136e+09,2.472054e+08,+39.0620324,-120.7227181,PLA,3,4.373307,...,17,280,2629,654,55,960,923,947,2032,1251
005,8,06005,Amador,1.539963e+09,2.945658e+07,+38.4435501,-120.6538563,AMA,10,2.909737,...,3,156,709,253,11,395,216,279,528,434
009,9,06009,Calaveras,2.641820e+09,4.381042e+07,+38.1878437,-120.5551154,CAL,10,2.963054,...,0,17,202,19,0,67,75,55,155,66
025,10,06025,Imperial,1.081735e+10,7.902479e+08,+33.0408155,-115.3553946,IMP,11,5.037553,...,29,3309,5448,7462,62,3459,4415,2302,10121,2789
093,11,06093,Siskiyou,1.625965e+10,1.798895e+08,+41.5879861,-122.5332868,SIS,2,7.291485,...,13,144,3331,262,26,830,922,1410,2364,1229
097,12,06097,Sonoma,4.081430e+09,4.975304e+08,+38.5325740,-122.9451943,SON,4,4.281978,...,16,190,3088,355,11,533,726,1983,1735,1708
085,13,06085,Santa Clara,3.341343e+09,3.617500e+07,+37.2207774,-121.6906224,SCL,4,3.549639,...,439,2963,45465,5285,342,5087,9920,31077,25302,25448
029,14,06029,Kern,2.106157e+10,7.957724e+07,+35.3466288,-118.7295064,KER,6,7.284303,...,29,748,4748,1494,58,1352,1838,2251,3783,2459
113,15,06113,Yolo,2.628032e+09,2.296918e+07,+38.6792682,-121.9031776,YOL,3,3.370275,...,13,236,1997,325,27,291,445,1387,1306,1016
045,16,06045,Mendocino,9.081386e+09,9.629526e+08,+39.4323876,-123.4428811,MEN,1,6.479724,...,12,117,1733,207,6,364,627,823,1109,831
067,17,06067,Sacramento,2.498416e+09,7.607725e+07,+38.4500114,-121.3404409,SAC,3,3.263035,...,509,3278,47279,5492,666,9653,12578,25470,28354,24417
039,18,06039,Madera,5.534983e+09,4.195750e+07,+37.2100387,-119.7498519,MAD,6,4.875881,...,1,115,435,262,5,198,158,246,411,286
115,19,06115,Yuba,1.636454e+09,3.099857e+07,+39.2700256,-121.3442802,YUB,3,2.842481,...,0,5,163,10,1,23,40,100,113,60
107,20,06107,Tulare,1.249466e+10,3.739162e+07,+36.2304529,-118.7805422,TUL,6,5.375810,...,12,846,4237,1577,60,1600,1686,1707,2992,2822
073,21,06073,San Diego,1.089512e+10,8.263479e+08,+33.0236041,-116.7761174,SD,11,6.113665,...,845,10732,75446,21006,1051,17690,26965,39696,59513,36939
063,22,06063,Plumas,6.612351e+09,1.563955e+08,+39.9951699,-120.8295155,PLU,2,5.270668,...,2,220,3355,347,26,711,1079,1356,2369,1333
069,23,06069,San Benito,3.596742e+09,4.555039e+06,+36.6107024,-121.0852960,SBT,5,3.706646,...,0,41,664,102,17,143,148,327,467,299
089,24,06089,Shasta,9.778247e+09,1.865309e+08,+40.7605215,-122.0435495,SHA,2,5.709524,...,19,289,7254,654,20,1437,2925,2777,5042,2866
099,25,06099,Stanislaus,3.871583e+09,5.143734e+07,+37.5623842,-121.0026557,STA,10,3.811884,...,18,357,2183,816,43,653,873,1159,1362,1637
043,26,06043,Mariposa,3.752417e+09,3.627140e+07,+37.5700335,-119.9128599,MPA,10,3.445756,...,24,259,6124,349,42,1409,1589,2348,3896,2577
019,27,06019,Fresno,1.543113e+10,1.378160e+08,+36.7610058,-119.6550193,FRE,6,9.003987,...,321,18145,46981,30080,1505,31695,21369,12063,25647,51414
003,28,06003,Alpine,1.912272e+09,1.255725e+07,+38.6176096,-119.7989986,ALP,10,2.174201,...,0,22,105,44,2,42,45,39,96,53
041,29,06041,Marin,1.347586e+09,7.974204e+08,+38.0518169,-122.7459738,MRN,4,3.699528,...,26,152,3032,245,17,542,622,1788,1755,1522
021,30,06021,Glenn,3.403107e+09,3.375020e+07,+39.6025462,-122.4016998,GLE,3,3.298067,...,4,119,1258,216,6,276,390,608,886,588
035,31,06035,Lassen,1.176161e+10,4.634407e+08,+40.7210889,-120.6299314,LAS,2,5.974202,...,17,180,2867,464,14,1223,957,763,2389,942
015,32,06015,Del Norte,2.606494e+09,5.785257e+08,+41.7499033,-123.9809983,DN,1,3.272597,...,1,33,834,53,1,280,268,247,592,295
055,33,06055,Napa,1.938247e+09,1.041693e+08,+38.5073511,-122.3259947,NAP,4,2.793204,...,2,50,629,68,5,132,197,308,388,309
079,34,06079,San Luis Obispo,8.543248e+09,8.209746e+08,+35.3852268,-120.4475404,SLO,5,6.405969,...,4,133,1511,308,19,373,341,855,1036,783
081,35,06081,San Mateo,1.161372e+09,7.577044e+08,+37.4146639,-122.3715417,SM,4,2.204525,...,174,869,14230,1319,160,1462,3228,9453,7672,7877
057,36,06057,Nevada,2.480617e+09,4.151494e+07,+39.2951907,-120.7734456,NEV,3,3.574954,...,8,135,1969,247,1,460,660,853,1331,885
077,37,06077,San Joaquin,3.603506e+09,9.110864e+07,+37.9350336,-121.2722369,SJ,10,3.261422,...,22,448,3294,872,55,817,1245,1700,1856,2310
071,38,06071,San Bernardino,5.194723e+10,1.240283e+08,+34.8572198,-116.1811967,SBD,8,10.453421,...,258,4845,32844,9100,780,8075,13000,16563,21934,20010
101,39,06101,Sutter,1.560236e+09,1.574700e+07,+39.0352571,-121.7027576,SUT,3,2.778648,...,5,47,417,91,1,91,154,227,214,294
065,40,06065,Riverside,1.866470e+10,2.510733e+08,+33.7298275,-116.0022389,RIV,8,7.951198,...,72,2015,11921,4398,335,4846,4372,5067,10427,5892
105,41,06105,Trinity,8.234230e+09,7.340786e+07,+40.6477241,-123.1144043,TRI,2,6.248589,...,10,62,602,110,11,177,175,269,426,286
013,42,06013,Contra Costa,1.854269e+09,2.274853e+08,+37.9194790,-121.9515431,CC,4,2.671683,...,248,1795,22667,2994,374,3294,7499,12249,10225,15436
111,43,06111,Ventura,4.773692e+09,9.459916e+08,+34.3587415,-119.1331432,VEN,7,3.249011,...,42,452,4057,1037,63,850,954,2634,2959,2135
109,44,06109,Tuolumne,5.752063e+09,1.386836e+08,+38.0214510,-119.9647084,TUO,10,5.076703,...,1,71,1641,144,8,360,594,623,1091,694
007,45,06007,Butte,4.238423e+09,1.053258e+08,+39.6659588,-121.6019188,BUT,3,4.205834,...,18,280,2963,528,7,737,978,1399,2086,1405
091,46,06091,Sierra,2.468814e+09,2.329911e+07,+39.5769252,-120.5219926,SIE,3,3.064025,...,0,14,162,29,0,79,32,68,79,112
033,47,06033,Lake,3.254228e+09,1.889623e+08,+39.0948019,-122.7467569,LAK,1,3.695965,...,8,60,428,126,3,169,200,106,365,189
049,48,06049,Modoc,1.014698e+10,7.397745e+08,+41.5929185,-120.7183704,MOD,2,4.539439,...,4,68,1661,156,14,387,537,612,1222,595
017,49,06017,El Dorado,4.423397e+09,2.032432e+08,+38.7855320,-120.5343981,ED,3,3.792236,...,6,106,1556,156,19,305,525,709,963,749
037,50,06037,Los Angeles,1.050987e+10,1.795013e+09,+34.1963983,-118.2618616,LA,7,6.322125,...,1246,18436,148526,38671,2275,35127,48846,80414,97046,90151
001,51,06001,Alameda,1.914046e+09,2.131846e+08,+37.6480811,-121.9133039,ALA,4,2.541576,...,386,2741,40169,4794,376,9932,10297,20986,22447,22516
027,52,06027,Inyo,2.636835e+10,1.192081e+08,+36.5619770,-117.4039269,INY,9,8.873319,...,18,150,2527,223,2,675,609,1108,1561,1189
075,53,06075,San Francisco,1.214000e+08,4.791903e+08,+37.7272391,-123.0322294,SF,4,0.829706,...,621,4344,69652,6818,528,8393,14854,46882,36519,39951
087,54,06087,Santa Cruz,1.152986e+09,4.195689e+08,+37.0124883,-122.0072050,SCR,5,2.404594,...,12,98,1449,213,3,119,244,1146,975,687
031,55,06031,Kings,3.598582e+09,5.468555e+06,+36.0724780,-119.8155301,KIN,6,2.879815,...,9,93,469,201,3,160,207,228,380,290
023,56,06023,Humboldt,9.241045e+09,1.254256e+09,+40.7066731,-123.9258181,HUM,1,6.231192,...,24,229,4772,292,21,890,1140,2450,3073,1991
095,57,06095,Solano,2.128361e+09,2.186659e+08,+38.2672255,-121.9395940,SOL,4,2.753327,...,76,355,4989,523,33,801,1543,2563,2505,3007
047,58,06047,Merced,5.011555e+09,1.127605e+08,+37.1948063,-120.7228019,MER,10,3.546949,...,3,255,1437,657,5,553,699,562,1356,738

## Use functions to do parameterized visualizations
* Use a function to create your chart
* Within the function, the colors should use the Cal-ITP theme that is available in `styleguide`
* Within the function, there should be at least 1 parameter that changes (ex: chart title reflects the correct county, legend title reflects the correct county, etc)
* Produce 3 charts, using your function each time, and have the function correctly insert the parameters

In [94]:
import altair as alt
from branca.colormap import LinearColormap

RED_GREEN_RANGE = ["#FF2020", "#EFF520", "#20FF20"]

def job_types_by_county(df: pd.DataFrame, three_digit_county_fips: str):
    jobs_in_county = df.loc[[three_digit_county_fips], :].copy()
    
    jobs_in_county_long = jobs_in_county.melt(
        id_vars=["OBJECTID", "GEOID10", "NAME10", "ALAND10", "AWATER10", "INTPTLAT10", "INTPTLON10", "CO_CODE", "DISTRICT", "SHAPE_Length", "SHAPE_Area", "geometry"],
        var_name="Category Code",
        value_name="# Jobs"
    )
    county_name = str.capitalize(jobs_in_county.at[three_digit_county_fips, "NAME10"])
    chart = alt.Chart(
        jobs_in_county_long, title=f"Federal Jobs in {county_name} by Categories"
    ).mark_bar(
        size=10
    ).encode(
        x=alt.X("Category Code"),
        y=alt.Y("# Jobs"),
        color=alt.Color("# Jobs").scale(domain=[jobs_in_county_long["# Jobs"].min(), jobs_in_county_long["# Jobs"].max()], range=RED_GREEN_RANGE)
    )
    return chart

In [95]:
for county_fips in ["087", "037", "073"]:
    job_types_by_county(counties_with_federal_jobs, county_fips)

alt.Chart(...)